// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 2.1.2,
// any modifications will be overwritten.
// ==============================================================

package top.mrxiaom.pluginbase.resolver.maven.model;

/**
 * Build configuration in a profile.
 * 
 * @version $Revision$ $Date$
 */
public class BuildBase
    extends PluginConfiguration
    implements java.io.Serializable, java.lang.Cloneable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * The default goal (or phase in Maven 2) to execute when none
     * is specified for
     *             the project. Note that in case of a multi-module
     * build, only the default goal of the top-level
     *             project is relevant, i.e. the default goals of
     * child modules are ignored. Since Maven 3,
     *             multiple goals/phases can be separated by
     * whitespace.
     */
    private String defaultGoal;

    /**
     * Field resources.
     */
    private java.util.List<Resource> resources;

    /**
     * Field testResources.
     */
    private java.util.List<Resource> testResources;

    /**
     * 
     *             The directory where all files generated by the
     * build are placed.
     *             The default value is <code>target</code>.
     *           
     */
    private String directory;

    /**
     * 
     *             
     *             The filename (excluding the extension, and with
     * no path information) that
     *             the produced artifact will be called.
     *             The default value is
     * <code>${artifactId}-${version}</code>.
     *             
     *           
     */
    private String finalName;

    /**
     * Field filters.
     */
    private java.util.List<String> filters;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     * 
     * @return BuildBase
     */
    public BuildBase clone()
    {
        try
        {
            BuildBase copy = (BuildBase) super.clone();

            if ( this.resources != null )
            {
                copy.resources = new java.util.ArrayList<>();
                for ( Resource item : this.resources )
                {
                    copy.resources.add( item.clone() );
                }
            }

            if ( this.testResources != null )
            {
                copy.testResources = new java.util.ArrayList<>();
                for ( Resource item : this.testResources )
                {
                    copy.testResources.add( item.clone() );
                }
            }

            if ( this.filters != null )
            {
                copy.filters = new java.util.ArrayList<>();
                copy.filters.addAll( this.filters );
            }

            return copy;
        }
        catch ( java.lang.Exception ex )
        {
            throw new UnsupportedOperationException( getClass().getName()
                + " does not support clone()", ex);
        }
    } //-- BuildBase clone()

    /**
     * Get the default goal (or phase in Maven 2) to execute when
     * none is specified for
     *             the project. Note that in case of a multi-module
     * build, only the default goal of the top-level
     *             project is relevant, i.e. the default goals of
     * child modules are ignored. Since Maven 3,
     *             multiple goals/phases can be separated by
     * whitespace.
     * 
     * @return String
     */
    public String getDefaultGoal()
    {
        return this.defaultGoal;
    } //-- String getDefaultGoal()

    /**
     * Get the directory where all files generated by the build are
     * placed.
     *             The default value is <code>target</code>.
     * 
     * @return String
     */
    public String getDirectory()
    {
        return this.directory;
    } //-- String getDirectory()

    /**
     * Method getFilters.
     * 
     * @return List
     */
    public java.util.List<String> getFilters()
    {
        if ( this.filters == null )
        {
            this.filters = new java.util.ArrayList<>();
        }

        return this.filters;
    } //-- java.util.List<String> getFilters()

    /**
     * Get the filename (excluding the extension, and with no path
     * information) that
     *             the produced artifact will be called.
     *             The default value is
     * <code>${artifactId}-${version}</code>.
     * 
     * @return String
     */
    public String getFinalName()
    {
        return this.finalName;
    } //-- String getFinalName()

    /**
     * Method getResources.
     * 
     * @return List
     */
    public java.util.List<Resource> getResources()
    {
        if ( this.resources == null )
        {
            this.resources = new java.util.ArrayList<>();
        }

        return this.resources;
    } //-- java.util.List<Resource> getResources()

    /**
     * Method getTestResources.
     * 
     * @return List
     */
    public java.util.List<Resource> getTestResources()
    {
        if ( this.testResources == null )
        {
            this.testResources = new java.util.ArrayList<>();
        }

        return this.testResources;
    } //-- java.util.List<Resource> getTestResources()

    /**
     * Set the default goal (or phase in Maven 2) to execute when
     * none is specified for
     *             the project. Note that in case of a multi-module
     * build, only the default goal of the top-level
     *             project is relevant, i.e. the default goals of
     * child modules are ignored. Since Maven 3,
     *             multiple goals/phases can be separated by
     * whitespace.
     * 
     * @param defaultGoal a defaultGoal object.
     */
    public void setDefaultGoal( String defaultGoal )
    {
        this.defaultGoal = defaultGoal;
    } //-- void setDefaultGoal( String )

    /**
     * Set the directory where all files generated by the build are
     * placed.
     *             The default value is <code>target</code>.
     * 
     * @param directory a directory object.
     */
    public void setDirectory( String directory )
    {
        this.directory = directory;
    } //-- void setDirectory( String )

    /**
     * Set the list of filter properties files that are used when
     * filtering is enabled.
     * 
     * @param filters a filters object.
     */
    public void setFilters( java.util.List<String> filters )
    {
        this.filters = filters;
    } //-- void setFilters( java.util.List )

    /**
     * Set the filename (excluding the extension, and with no path
     * information) that
     *             the produced artifact will be called.
     *             The default value is
     * <code>${artifactId}-${version}</code>.
     * 
     * @param finalName a finalName object.
     */
    public void setFinalName( String finalName )
    {
        this.finalName = finalName;
    } //-- void setFinalName( String )

    /**
     * Set this element describes all of the classpath resources
     * such as properties
     *             files associated with a project. These resources
     * are often included in the final
     *             package.
     *             The default value is
     * <code>src/main/resources</code>.
     * 
     * @param resources a resources object.
     */
    public void setResources( java.util.List<Resource> resources )
    {
        this.resources = resources;
    } //-- void setResources( java.util.List )

    /**
     * Set this element describes all of the classpath resources
     * such as properties
     *             files associated with a project's unit tests.
     *             The default value is
     * <code>src/test/resources</code>.
     * 
     * @param testResources a testResources object.
     */
    public void setTestResources( java.util.List<Resource> testResources )
    {
        this.testResources = testResources;
    } //-- void setTestResources( java.util.List )

    
            
    /**
     * @see java.lang.Object#toString()
     */
    public String toString()
    {
        return "BuildBase {" + super.toString() + "}";
    }
            
          
}
