// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 2.1.2,
// any modifications will be overwritten.
// ==============================================================

package top.mrxiaom.pluginbase.resolver.maven.model;

/**
 * Information about one of the committers on this project.
 * 
 * @version $Revision$ $Date$
 */
public class Developer
    extends Contributor
    implements java.io.Serializable, java.lang.Cloneable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * The unique ID of the developer in the SCM.
     */
    private String id;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     * 
     * @return Developer
     */
    public Developer clone()
    {
        try
        {
            return (Developer) super.clone();
        }
        catch ( java.lang.Exception ex )
        {
            throw new UnsupportedOperationException( getClass().getName()
                + " does not support clone()", ex);
        }
    } //-- Developer clone()

    /**
     * Get the unique ID of the developer in the SCM.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Set the unique ID of the developer in the SCM.
     * 
     * @param id a id object.
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    
            
    /**
     * @see java.lang.Object#toString()
     */
    public String toString()
    {
        return "Developer {id=" + id + ", " + super.toString() + "}";
    }
            
          
}
