// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 2.1.2,
// any modifications will be overwritten.
// ==============================================================

package top.mrxiaom.pluginbase.resolver.maven.model;

/**
 * Section for management of default plugin information for use in
 * a group of POMs.
 *       
 * 
 * @version $Revision$ $Date$
 */
public class PluginManagement
    extends PluginContainer
    implements java.io.Serializable, java.lang.Cloneable
{

      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     * 
     * @return PluginManagement
     */
    public PluginManagement clone()
    {
        try
        {
            return (PluginManagement) super.clone();
        }
        catch ( java.lang.Exception ex )
        {
            throw new UnsupportedOperationException( getClass().getName()
                + " does not support clone()", ex);
        }
    } //-- PluginManagement clone()

}
